version: '3'
services:
  dev:
    build: .
    command: yarn dev
    ports:
      - "8080:8080"
    env_file:
      - .env
  web:
    build: .
    command: yarn start
    ports:
      - "8080:8080"
    env_file:
      - .env
  mongo:
    image: mongo
    ports:
      - 27017:27017

      